
services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:v1
    container_name: nginx
    ports:
        - "443:443"
    # volumes:
    #     - /home/aaghbal/data:/var/www/wordpress
    restart: always 
    networks:
    - inception
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:v1
    container_name: mariadb
    expose:
        - "3306"
    env_file: .env
    restart: always
    # volumes:
    #     - /home/aaghbal/db:/var/lib/mysql
    networks:
    - inception
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:v1
    container_name: wordpress
    expose:
        - "9000"
    env_file: .env
    networks:
    - inception
    depends_on:
      - mariadb
    restart: always
    # volumes:
    #     - /home/aaghbal/data:/var/www/wordpress
volumes:
  data:
  db:

networks:
  inception:
    name: inception
    driver: bridge