
services:

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:v1
    container_name: nginx
    ports:
        - "443:443"
    volumes:
        - data:/var/www/wordpress
    restart: always 
    networks:
    - inception
  
  
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:v1
    container_name: mariadb
    expose:
        - "3306"
    env_file: .env
    restart: always
    volumes:
        - db:/var/lib/mysql
    networks:
    - inception


  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:v1
    container_name: wordpress
    expose:
        - "9000"
    env_file: .env
    networks:
    - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
        - data:/var/www/wordpress


  website:
    build:
      context: ./requirements/bonus/website
    image: website:v1
    container_name: website
    ports:
        - "1000:443"
    restart: always

volumes:
  data:
    name: wp_ngi
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaghbal/data 
  db:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaghbal/db

networks:
  inception:
    name: inception
    driver: bridge